In [49]:
import pandas as pd

df = pd.read_csv('Emotion_classify_data.csv')
df.shape

(5937, 2)

In [50]:
df.head()

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [51]:
df.Emotion.value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [52]:
df['Emotion_num'] = df['Emotion'].map({'joy' : 0, 'fear': 1, 'anger': 2})

In [53]:
df.head()

                                             Comment Emotion  Emotion_num
0  i seriously hate one subject to death but now ...    fear            1
1                 im so full of life i feel appalled   anger            2
2  i sit here to write i start to dig out my feel...    fear            1
3  ive been really angry with r and i feel like a...     joy            0
4  i feel suspicious if there is no one outside l...    fear            1

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train,X_test,y_train, y_test  = train_test_split(
    df.Comment,
    df.Emotion_num,
    test_size=0.2,
    random_state=2022,
    stratify=df.Emotion_num
)

print(X_train.shape)
print(X_test.shape)

(4749,)
(1188,)

In [55]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer 

clf = Pipeline([
    ('count_vec',CountVectorizer(ngram_range=(3,3))),
    ('rand_forest', (RandomForestClassifier()))
])

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.59      0.28      0.38       400
           1       0.38      0.79      0.51       388
           2       0.55      0.25      0.35       400

    accuracy                           0.44      1188
   macro avg       0.50      0.44      0.41      1188
weighted avg       0.51      0.44      0.41      1188

In [56]:
from sklearn.naive_bayes import MultinomialNB

clf = Pipeline([
    ('count_vec',CountVectorizer(ngram_range=(1,2))),
    ('multiNB', (MultinomialNB()))
])

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.86      0.87       400
           1       0.87      0.83      0.85       388
           2       0.83      0.88      0.85       400

    accuracy                           0.86      1188
   macro avg       0.86      0.86      0.86      1188
weighted avg       0.86      0.86      0.86      1188

In [57]:

clf = Pipeline([
    ('count_vec',CountVectorizer(ngram_range=(1,2))),
    ('randForest', (RandomForestClassifier()))
])

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.96      0.89       400
           1       0.95      0.87      0.91       388
           2       0.95      0.85      0.90       400

    accuracy                           0.90      1188
   macro avg       0.90      0.90      0.90      1188
weighted avg       0.90      0.90      0.90      1188

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

clf = Pipeline([
    ('tfidfVect', (TfidfVectorizer())),
    ('randFore',RandomForestClassifier()),
])

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91       400
           1       0.90      0.92      0.91       388
           2       0.94      0.86      0.90       400

    accuracy                           0.91      1188
   macro avg       0.91      0.91      0.91      1188
weighted avg       0.91      0.91      0.91      1188

In [59]:
import spacy

nlp = spacy.load("en_core_web_sm")

def preProcess(text):
    doc = nlp(text)
    filtered_tokens = []

    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)

    return " ".join(filtered_tokens)

In [60]:
df['preprocessed_comment'] = df['Comment'].apply(preProcess)

In [61]:
df.head()

,Comment,Emotion,Emotion_num,preprocessed_comment
0,i seriously hate one subject to death but now ...,fear,1,seriously hate subject death feel reluctant drop
1,im so full of life i feel appalled,anger,2,m life feel appalled
2,i sit here to write i start to dig out my feel...,fear,1,sit write start dig feeling think afraid accep...
3,ive been really angry with r and i feel like a...,joy,0,ve angry r feel like idiot trust place
4,i feel suspicious if there is no one outside l...,fear,1,feel suspicious outside like rapture happen

In [62]:
X_train,X_test,y_train, y_test  = train_test_split(
    df.preprocessed_comment,
    df.Emotion_num,
    test_size=0.2,
    random_state=2022,
    stratify=df.Emotion_num
)

print(X_train.shape)
print(X_test.shape)

(4749,)
(1188,)

In [63]:

clf = Pipeline([
    ('count_vec',CountVectorizer(ngram_range=(1,2))),
    ('randForest', (RandomForestClassifier()))
])

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.95      0.94       400
           1       0.94      0.90      0.92       388
           2       0.91      0.94      0.92       400

    accuracy                           0.93      1188
   macro avg       0.93      0.93      0.93      1188
weighted avg       0.93      0.93      0.93      1188

In [64]:

clf = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('randForest', (RandomForestClassifier()))
])

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.96      0.93       400
           1       0.94      0.91      0.92       388
           2       0.93      0.91      0.92       400

    accuracy                           0.93      1188
   macro avg       0.93      0.93      0.93      1188
weighted avg       0.93      0.93      0.93      1188