In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('movies_sentiment_data.csv')

df.shape

(19000, 2)

In [4]:
df.head()

                                              review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [9]:
df['Category'] = df['sentiment'].apply(lambda x : 1 if x =="positive" else 0)

In [11]:
df.head()

                                              review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [12]:
df['Category'].value_counts()

Category
1    9500
0    9500
Name: count, dtype: int64

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.review, df.Category, test_size=0.2)

Exercise-1

using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.
Note:

use CountVectorizer for pre-processing the text.

use Random Forest as the classifier with estimators as 50 and criterion as entropy.

print the classification report.

In [16]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('random_forest', (RandomForestClassifier(n_estimators=50, criterion='entropy')))

])

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.84      0.84      1903
           1       0.84      0.85      0.84      1897

    accuracy                           0.84      3800
   macro avg       0.84      0.84      0.84      3800
weighted avg       0.84      0.84      0.84      3800

In [17]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('KNN', (KNeighborsClassifier(n_neighbors=10, metric='euclidean')))
])

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.65      0.64      0.65      1903
           1       0.64      0.65      0.65      1897

    accuracy                           0.65      3800
   macro avg       0.65      0.65      0.65      3800
weighted avg       0.65      0.65      0.65      3800

In [18]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('Multi NB', MultinomialNB())
])

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1903
           1       0.87      0.82      0.84      1897

    accuracy                           0.85      3800
   macro avg       0.85      0.85      0.85      3800
weighted avg       0.85      0.85      0.85      3800